### PR TITLE
Add workflow for PRs

### PR DESCRIPTION
**Pull request by hdost**

### CODE REVIEW

**Comment by hdost** [comment]
I think that creating this separate workflow might just work Since the other workflow requires secrets there was mention in the page before about how secret sharing has to be enable for forked repos to work, but I think that's on a workflow by workflow basis. If this workflow doesn't have secrets, which it should not need, then it should work on the next PR.

**Comment by hdost** [comment]
@Dieterbe

**Comment by Dieterbe** [comment]
strange, i don't see docs for this. can you link me?

**Comment by hdost** [comment]
https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests

> Note: Forked PR builds of open source projects that require secrets will not run successfully on CircleCI until you enable this setting.

What i read from this is since the workflow that currently exists requires secrets it won't work unless A. Secrets are shared. I wouldn't recommend this because people could fork and then just echo out params or otherwise extract them.
B Create a second workflow where secrets are not required.

**Comment by hdost** [comment]
This has apparently been unclear for a bit now https://github.com/circleci/circleci-docs/issues/3974

**Comment by Dieterbe** [comment]
Aha I see. ok I was searching for `pr_acceptance` in the CircleCI docs which of course don't result in anything because that's just the custom name you gave the workflow. that makes sense now :)

let's try this. Agreed with not wanting to provide secrets to forked repo's.

**Pull request merged**
